### ISSUE TITLE
AKO failing when looking for tls cert 

### ISSUE THREAD

**Issue by jfwm2** [aerospike/aerospike-kubernetes-operator#76] opened 2021-09-08 15:41 UTC
Hello

I am trying to run the last version of the operator (upgrade for version 1.0.1 to head of repository),  but it fails when being deployed. Here are the logs; do you have an idea of what went wrong?

Thanks

```2021-09-08T15:32:49.342Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2021-09-08T15:32:49.342Z	INFO	setup	Init aerospike-server config schemas
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.0.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.5.3
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.6.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.7.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=5.0.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.1.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.2.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.3.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.3.1
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.4.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.5.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=5.2.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=5.3.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=5.5.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=5.6.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.5.1
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.8.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.9.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=5.1.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=5.4.0
t=2021-09-08T15:32:49+0000 lvl=dbug msg="Config schema added" module=lib.asconfig version=4.5.2
2021-09-08T15:32:49.346Z	INFO	aerospikecluster-resource	registering mutating webhook to the webhook server
2021-09-08T15:32:49.346Z	INFO	controller-runtime.webhook	registering webhook	{"path": "/mutate-asdb-aerospike-com-v1beta1-aerospikecluster"}
2021-09-08T15:32:49.346Z	INFO	controller-runtime.builder	skip registering a mutating webhook, admission.Defaulter interface is not implemented	{"GVK": "asdb.aerospike.com/v1beta1, Kind=AerospikeCluster"}
2021-09-08T15:32:49.346Z	INFO	controller-runtime.builder	Registering a validating webhook	{"GVK": "asdb.aerospike.com/v1beta1, Kind=AerospikeCluster", "path": "/validate-asdb-aerospike-com-v1beta1-aerospikecluster"}
2021-09-08T15:32:49.346Z	INFO	controller-runtime.webhook	registering webhook	{"path": "/validate-asdb-aerospike-com-v1beta1-aerospikecluster"}
2021-09-08T15:32:49.346Z	INFO	setup	starting manager
2021-09-08T15:32:49.346Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
2021-09-08T15:32:49.346Z	INFO	controller-runtime.webhook.webhooks	starting webhook server
2021-09-08T15:32:49.346Z	INFO	controller-runtime.manager.controller.aerospikecluster	Starting EventSource	{"reconciler group": "asdb.aerospike.com", "reconciler kind": "AerospikeCluster", "source": "kind source: /, Kind="}
2021-09-08T15:32:49.346Z	INFO	controller-runtime.manager.controller.aerospikecluster	Starting EventSource	{"reconciler group": "asdb.aerospike.com", "reconciler kind": "AerospikeCluster", "source": "kind source: /, Kind="}
2021-09-08T15:32:49.346Z	INFO	controller-runtime.manager.controller.aerospikecluster	Starting Controller	{"reconciler group": "asdb.aerospike.com", "reconciler kind": "AerospikeCluster"}
2021-09-08T15:32:49.346Z	ERROR	controller-runtime.manager.controller.aerospikecluster	Could not wait for Cache to sync	{"reconciler group": "asdb.aerospike.com", "reconciler kind": "AerospikeCluster", "error": "failed to wait for aerospikecluster caches to sync: timed out waiting for cache to be synced"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:195
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:221
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/manager/internal.go:696
2021-09-08T15:32:49.346Z	ERROR	setup	problem running manager	{"error": "open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory"}
main.main
	/workspace/main.go:144
runtime.main
	/usr/local/go/src/runtime/proc.go:225
```

**Comment by sud82** [comment] 2021-11-10 13:15
Hi @jfwm2, Sorry for the late response. Are you still facing the issue or this has started working?

**Comment by adumovic** [comment] 2021-11-24 17:03
I know its not the same version, or probably officially supported, but I am seeing the exact same thing on version 2.0.0-rc1 (I was trying it out since it seems to add support for tolerations). After destroying the 1.0.1 and deploying 2.0.0-rc1, the container is stuck in crash loop backoff with the same errors as above:
```
2021-11-24T06:56:25.397228704Z 2021-11-24T06:56:25.397Z	DEBUG	schema-map	Config schema added	{"version": "4.3.0"}
2021-11-24T06:56:25.397210870Z 2021-11-24T06:56:25.397Z	DEBUG	schema-map	Config schema added	{"version": "4.2.0"}
2021-11-24T06:56:25.397207285Z 2021-11-24T06:56:25.397Z	DEBUG	schema-map	Config schema added	{"version": "4.1.0"}
2021-11-24T06:56:25.397203629Z 2021-11-24T06:56:25.397Z	DEBUG	schema-map	Config schema added	{"version": "4.0.0"}
2021-11-24T06:56:25.397197934Z 2021-11-24T06:56:25.397Z	DEBUG	schema-map	Config schema added	{"version": "5.4.0"}
2021-11-24T06:56:25.397558390Z 2021-11-24T06:56:25.397Z	INFO	aerospikecluster-resource	Registering mutating webhook to the webhook server
2021-11-24T06:56:25.397682790Z 2021-11-24T06:56:25.397Z	INFO	controller-runtime.webhook	registering webhook	{"path": "/mutate-asdb-aerospike-com-v1beta1-aerospikecluster"}
2021-11-24T06:56:25.397753872Z 2021-11-24T06:56:25.397Z	INFO	controller-runtime.builder	skip registering a mutating webhook, admission.Defaulter interface is not implemented	{"GVK": "asdb.aerospike.com/v1beta1, Kind=AerospikeCluster"}
2021-11-24T06:56:25.397778359Z 2021-11-24T06:56:25.397Z	INFO	controller-runtime.builder	Registering a validating webhook	{"GVK": "asdb.aerospike.com/v1beta1, Kind=AerospikeCluster", "path": "/validate-asdb-aerospike-com-v1beta1-aerospikecluster"}
2021-11-24T06:56:25.397803068Z 2021-11-24T06:56:25.397Z	INFO	controller-runtime.webhook	registering webhook	{"path": "/validate-asdb-aerospike-com-v1beta1-aerospikecluster"}
2021-11-24T06:56:25.397883949Z 2021-11-24T06:56:25.397Z	INFO	setup	Starting manager
2021-11-24T06:56:25.398210780Z 2021-11-24T06:56:25.398Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
2021-11-24T06:56:25.398372833Z 2021-11-24T06:56:25.398Z	INFO	controller-runtime.webhook.webhooks	starting webhook server
2021-11-24T06:56:25.398400770Z 2021-11-24T06:56:25.398Z	INFO	controller-runtime.manager.controller.aerospikecluster	Starting EventSource	{"reconciler group": "asdb.aerospike.com", "reconciler kind": "AerospikeCluster", "source": "kind source: /, Kind="}
2021-11-24T06:56:25.398416951Z 2021-11-24T06:56:25.398Z	INFO	controller-runtime.manager.controller.aerospikecluster	Starting EventSource	{"reconciler group": "asdb.aerospike.com", "reconciler kind": "AerospikeCluster", "source": "kind source: /, Kind="}
2021-11-24T06:56:25.398424801Z 2021-11-24T06:56:25.398Z	INFO	controller-runtime.manager.controller.aerospikecluster	Starting Controller	{"reconciler group": "asdb.aerospike.com", "reconciler kind": "AerospikeCluster"}
2021-11-24T06:56:25.398523994Z 2021-11-24T06:56:25.398Z	ERROR	controller-runtime.manager.controller.aerospikecluster	Could not wait for Cache to sync	{"reconciler group": "asdb.aerospike.com", "reconciler kind": "AerospikeCluster", "error": "failed to wait for aerospikecluster caches to sync: timed out waiting for cache to be synced"}
2021-11-24T06:56:25.398543508Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
2021-11-24T06:56:25.398550124Z 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:195
2021-11-24T06:56:25.398555706Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
2021-11-24T06:56:25.398561177Z 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:221
2021-11-24T06:56:25.398566690Z sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1
2021-11-24T06:56:25.398585225Z 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/manager/internal.go:696 
2021-11-24T06:56:25.398590416Z 2021-11-24T06:56:25.398Z	ERROR	controller-runtime.manager	error received after stop sequence was engaged	{"error": "failed to wait for aerospikecluster caches to sync: timed out waiting for cache to be synced"}
2021-11-24T06:56:25.398621618Z 2021-11-24T06:56:25.398Z	ERROR	setup	problem running manager	{"error": "open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory"}
2021-11-24T06:56:25.398639665Z main.main
2021-11-24T06:56:25.398644353Z 	/workspace/main.go:145
2021-11-24T06:56:25.398648838Z runtime.main
2021-11-24T06:56:25.398653133Z 	/usr/local/go/src/runtime/proc.go:225
```

**Comment by jfwm2** [comment] 2021-11-25 07:42
> Hi @jfwm2, Sorry for the late response. Are you still facing the issue or this has started working?

Hello @sud82, We did not have a chance to test it again. I will let you know when we try again.

**Comment by jfwm2** [comment] 2021-11-25 07:43
> I know its not the same version, or probably officially supported, but I am seeing the exact same thing on version 2.0.0-rc1 
...

Hello @adumovic, I believe it is the same version (it was just not tagged yet at the time I was trying)

**Comment by ashishshinde** [comment] 2021-11-25 17:28
@jfwm2 @adumovic How is the operator being installed? If via helm, has cert manager being installed?

https://github.com/aerospike/aerospike-kubernetes-operator/tree/master/helm-charts/aerospike-kubernetes-operator#deploy-cert-manager

**Comment by adumovic** [comment] 2021-12-01 17:13
@ashishshinde  I completely missed these steps in setup, as i don't believe they were part of 1.0.1 deployment. I will make sure to go over the steps in the readme for 2.0.0. I will let you know what happens, but i expect the cert manager to resolve my issues.

Also just out of curiosity, i see 2.0.0 just made RC2, and has support for server version 5.7, any ETA on the official release date?

**Comment by ashishshinde** [comment] 2021-12-17 08:12
@adumovic Hope the issue is resolved. 

> Also just out of curiosity, i see 2.0.0 just made RC2, and has support for server version 5.7, any ETA on the official release date?

Yes 2.0.0-rc2 has support for Aerospike server 5.7

**Comment by arrowplum** [comment] 2022-01-04 18:31
Closing this as it looks like it has been resolved.

**Closed by arrowplum** 2022-01-04 18:31 UTC
